#!/usr/bin/env bash
# secdash installer — read-only security dashboard, bound to your tailnet.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/Alpinho97/secdash/main/install.sh | sudo bash
#
# Or with options:
#   curl -fsSL https://raw.githubusercontent.com/Alpinho97/secdash/main/install.sh | sudo bash -s -- --port 8765
#
# Flags:
#   --bind IP        Bind to this IP. Default: tailscale0 IP, fallback 127.0.0.1.
#   --port N         Port to listen on. Default: 8765.
#   --ref REF        git ref to install (branch/tag/commit). Default: main.
#   --no-debsecan    Skip debsecan install (no CVE data).
#   --uninstall      Remove the service and /opt/secdash.
#
set -euo pipefail

REPO="Alpinho97/secdash"
REPO_URL="https://github.com/${REPO}.git"
DEST=/opt/secdash
ENV_DIR=/etc/secdash
ENV_FILE=${ENV_DIR}/secdash.env
UNIT_PATH=/etc/systemd/system/secdash.service
DEFAULT_PORT=8765

BIND=""
PORT=${DEFAULT_PORT}
REF=main
SKIP_DEBSECAN=0
UNINSTALL=0

usage() {
  cat <<'USAGE'
secdash installer — read-only security dashboard, bound to your tailnet.

Usage:
  curl -fsSL https://raw.githubusercontent.com/Alpinho97/secdash/main/install.sh | sudo bash
  curl -fsSL https://raw.githubusercontent.com/Alpinho97/secdash/main/install.sh | sudo bash -s -- --port 8765

Flags:
  --bind IP        Bind to this IP. Default: tailscale0 IP, fallback 127.0.0.1.
  --port N         Port to listen on. Default: 8765.
  --ref REF        git ref to install (branch/tag/commit). Default: main.
  --no-debsecan    Skip debsecan install (no CVE data).
  --uninstall      Remove the service and /opt/secdash.
  -h, --help       Show this help.
USAGE
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bind) BIND="$2"; shift 2;;
    --port) PORT="$2"; shift 2;;
    --ref)  REF="$2"; shift 2;;
    --no-debsecan) SKIP_DEBSECAN=1; shift;;
    --uninstall) UNINSTALL=1; shift;;
    -h|--help) usage 0;;
    *) echo "Unknown option: $1" >&2; usage 1;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "secdash installer must run as root. Try: sudo $0 $*" >&2
  exit 1
fi

log() { printf "\033[1;34m[secdash]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[secdash]\033[0m %s\n" "$*" >&2; }
die() { printf "\033[1;31m[secdash]\033[0m %s\n" "$*" >&2; exit 1; }

if [[ ${UNINSTALL} -eq 1 ]]; then
  log "Uninstalling secdash"
  systemctl disable --now secdash.service 2>/dev/null || true
  rm -f "${UNIT_PATH}"
  systemctl daemon-reload
  rm -rf "${DEST}" "${ENV_DIR}"
  log "Removed."
  exit 0
fi

# ---- Detect bind IP ----
if [[ -z "${BIND}" ]]; then
  if command -v tailscale >/dev/null && tailscale ip -4 >/dev/null 2>&1; then
    BIND=$(tailscale ip -4 | head -n1)
    log "Detected tailscale0 IP: ${BIND}"
  else
    BIND=127.0.0.1
    warn "Tailscale not detected; binding to ${BIND}. Reach via SSH tunnel."
  fi
fi

# Validate
if ! [[ "${BIND}" =~ ^[0-9a-fA-F.:]+$ ]]; then
  die "Invalid --bind value: ${BIND}"
fi
if ! [[ "${PORT}" =~ ^[0-9]+$ ]] || [[ ${PORT} -lt 1 ]] || [[ ${PORT} -gt 65535 ]]; then
  die "Invalid --port value: ${PORT}"
fi

log "Will install to ${DEST}, bind to ${BIND}:${PORT}, git ref '${REF}'"

# ---- Dependencies ----
log "Installing apt dependencies"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
PKGS=(git python3 python3-venv ca-certificates openssl iproute2)
[[ ${SKIP_DEBSECAN} -eq 0 ]] && PKGS+=(debsecan)
apt-get install -y -qq "${PKGS[@]}"

# ---- Fetch source ----
log "Fetching source (ref=${REF})"
TMP=$(mktemp -d)
trap 'rm -rf "${TMP}"' EXIT
git clone --depth 1 --branch "${REF}" "${REPO_URL}" "${TMP}/src" 2>&1 | sed 's/^/  /'
SRC=${TMP}/src

# ---- Layout ----
log "Syncing files into ${DEST}"
mkdir -p "${DEST}"
if command -v rsync >/dev/null; then
  rsync -a --delete "${SRC}/app/" "${DEST}/app/"
else
  rm -rf "${DEST}/app"
  cp -r "${SRC}/app" "${DEST}/app"
fi

# ---- Venv ----
if [[ ! -x "${DEST}/venv/bin/python" ]]; then
  log "Creating venv"
  python3 -m venv "${DEST}/venv"
fi
log "Installing python dependencies"
"${DEST}/venv/bin/pip" install --quiet --upgrade pip
"${DEST}/venv/bin/pip" install --quiet "fastapi>=0.110" "uvicorn[standard]>=0.27" "jinja2>=3"

# ---- Env file ----
mkdir -p "${ENV_DIR}"
chmod 0755 "${ENV_DIR}"
cat > "${ENV_FILE}" <<EOF
# Generated by secdash installer; safe to edit + 'systemctl restart secdash'
SECDASH_HOST=${BIND}
SECDASH_PORT=${PORT}
EOF
chmod 0644 "${ENV_FILE}"

# ---- systemd unit ----
log "Installing systemd unit"
install -m 0644 "${SRC}/secdash.service" "${UNIT_PATH}"
systemctl daemon-reload
systemctl enable --now secdash.service

# ---- Verify ----
sleep 2
if systemctl is-active --quiet secdash.service; then
  log "service: active"
else
  warn "service: NOT ACTIVE — see 'journalctl -u secdash -n 50'"
  exit 1
fi

# Quick HTTP probe
if command -v curl >/dev/null; then
  CODE=$(curl -fsS -o /dev/null -m 5 -w "%{http_code}" "http://${BIND}:${PORT}/healthz" 2>/dev/null || echo "000")
  if [[ "${CODE}" == "200" ]]; then
    log "HTTP healthz: 200 OK"
  else
    warn "HTTP healthz returned: ${CODE}"
  fi
fi

cat <<EOF

╭─ secdash installed ───────────────────────────────────────╮
│  Dashboard:  http://${BIND}:${PORT}/
│  Service:    systemctl status secdash
│  Logs:       journalctl -u secdash -f
│  Config:     ${ENV_FILE}
│  Uninstall:  curl -fsSL https://raw.githubusercontent.com/${REPO}/${REF}/install.sh | sudo bash -s -- --uninstall
╰───────────────────────────────────────────────────────────╯
EOF
